version: '3'

services:
  splunk:
    image: splunk/splunk:latest
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: <YourPassword>
      SPLUNK_USER: <YourUsername>
    ports:
      - "8000:8000"
      - "8088:8088"
    volumes:
      - splunk-data:/opt/splunk/etc
      - splunk-logs:/opt/splunk/var/log

volumes:
  splunk-data:
  splunk-logs:
