version: '3.7'

services:
  metasploitable:
    image: tleemcjr/metasploitable2:latest
    networks:
      - mynetwork
    tty: true

  hack:
    image: ghcr.io/vr0n/grasshopper:v1.2
    networks:
      - mynetwork
    tty: true

networks:
  mynetwork:
    driver: bridge
