version: '3'

services:
  metasploitable:
    image: vulnerables/web-dvwa:latest
    ports:
      - "80:80"
    networks:
      mynetwork:
        ipv4_address: 172.16.1.100

  redis:
    image: redis:5.0.9-alpine
    networks:
      mynetwork:
        ipv4_address: 172.16.1.2

  postgresql:
    image: postgres:12-alpine
    environment:
    - POSTGRES_USER=gitlab
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=gitlabhq_production
    - DB_EXTENSION=pg_trgm,btree_gist

  gitlab:
    image: vulhub/gitlab:13.10.1
    depends_on:
    - redis
    - postgresql
    ports:
    - "8080:80"
    - "10022:22"
    environment:
    - DEBUG=false

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - GITLAB_HTTPS=false
    - SSL_SELF_SIGNED=false

    - GITLAB_HOST=localhost
    - GITLAB_PORT=8080
    - GITLAB_SSH_PORT=10022
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_SECRETS_DB_KEY_BASE=secret-key
    - GITLAB_SECRETS_SECRET_KEY_BASE=secret-key
    - GITLAB_SECRETS_OTP_KEY_BASE=secret-key

    - TZ=Asia/Kolkata
    - GITLAB_TIMEZONE=Kolkata
    - GITLAB_ROOT_PASSWORD=vulhub123456
    networks:
      mynetwork:
        ipv4_address: 172.16.1.10

  kali:
    image: kalilinux/kali-rolling
    command:
      sh -c "apt update && apt -y install kali-linux-headless"
    ports:
      - "22:22"
    networks:
      - mynetwork
    tty: true


networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

volumes:
  splunk-data:
  splunk-logs:
